### ISSUE TITLE
TAs Appearing in the GB's Spreadsheet View/Export CSV

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#139]
Just noticed this when testing import/export, and wanted to raise this really quick:

It looks like users with the role of "Teaching Assistant" are currently appearing as students to be graded within the spreadsheet interface.
- Site Info screen: http://www.screencast.com/t/GLr6FJVil
- New Gradebook Grades view: http://www.screencast.com/t/Mog5FYcI
- GB Classic view: http://www.screencast.com/t/nM8CHedYN7e1

Any TA's in the new GB are also appearing in exported CSV files.

**Comment by steveswinsburg** [comment]
Ok this explains the issue of the grades not appearing as well. We fetch the grades for all students per assignment. So if one of those users throws the exception, the assignment is skipped. So when you had that student viewing it, it showed nothing as they didn't have permission. And when you were instructor it was also throwing the error because TAs were in the list.

As discussed, when you pass in the list of users to get grades, the GradebookService goes off and gets the users again and checks the ones passed in are in the allowed list. If not, exception which leads to skipping.

I think there is a mismatch in how we get the users that can have grades and the way the gradebook service is expecting them. We use the method that gets them all based on a permission, I think if we tweak this to match we should be good.

**Comment by steveswinsburg** [comment]
Ok this should be done and will appear on nightly soon, @kyleblythe can you please confirm? This should also fix the issue you saw with the scores not appearing. If so, high fives all round.
