### ISSUE TITLE
Additions to "Add Gradebook Item"

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#176]
A few additions/tweaks to the "Add Gradebook Item" screen and resulting item creation:
- Category info note when GB is not set with categories or cat & weighting: Rather than provide an empty dropdown menu or no category info at all, provide a note stating "No categories have been created."
- Category percentage: If categories & weighting are in place, provide the category's percentage in parentheses next to the category name in the dropdown menu (e.g., Homework (30%) )
- Item placement when grouped by category: When a new item is created and the GB is grouped by category, place the newly created item to the far-right of whichever category it belongs to.
- Auto-scrolling to placement of new item, with temporary highlight of new item: When a new item is added, scroll the GB interface so as to make the new item visible to the user. Additionally, if possible, provide some sort of temporary highlighting to make the newly created item more immediately visible (perhaps a bolded border).

**Comment by kyleblythe** [comment]
Hi @payten,

The category info / percentage and auto-scrolling are looking great. The only thing I'm still noticing is, when grouped by category, the newly created GB item doesn't appear to be getting added on the far-right (bullet 3 above):

![2015-09-09_14-43-31](https://cloud.githubusercontent.com/assets/11447474/9771013/588d69da-5701-11e5-8c54-733883673ebd.png)

**Comment by payten** [comment]
Hi @steveswinsburg, in regard to #216, this is pretty much done in the Javascript at present as the category order XML isn't always in sync with reality.  Ideally we would update the `GradebookNgBusinessService.addAssignment` method to at least try and keep the XML more in sync, however as assignments can be imported and also created via the old Gradebook tool it completely bypasses our service leaving the XML in a dodgy state.

I've currently solved it by sorting by the index from the XML if it was present.  If assignments aren't in the XML they have an index of `-1` and they are pushed to the end by default.  If any assignments have the same index (`-1` or otherwise), we order by the assignment's ID in ascending order, ensuring newer assignments are at the end.

**Comment by steveswinsburg** [comment]
Yeah I don't think we can do much about the order unless we get this
sorting into the backend, which requires more complex changes.
But this is great for now.

cheers,
Steve

**Comment by kyleblythe** [comment]
Confirmed!
