### ISSUE TITLE
"-" as Course Grade when no scores are present for student

### ISSUE THREAD

**Issue by kyleblythe** [steveswinsburg/gradebookNG#237]
When no scores have been provided for a student (and their course grade therefore is a null value), provide a dash (i.e., - ) as the displayed value in that student's "Course Grade" column, replacing the current "F."

**Comment by steveswinsburg** [comment]
I think this needs to go into the gradebook service as it is there where the course grade is calculated.

**Comment by steveswinsburg** [comment]
The ‘F’ comes from the gradebook service and any change to this would be a modification to the gradebook service which may affect other tools. We should just handle this in our business service and override the course grade if there are no grades for the student.

**Comment by steveswinsburg** [comment]
Pushed a fix for this. If the student has no grades entered the course grade is overriden to a -

**Comment by kyleblythe** [comment]
Hi @steveswinsburg ,

In a fresh course site w/ gradebook items and no scores, the dashes are showing up. However, in an existing site, students that at one point had scores that have since been deleted are still showing a course grade of "F":

![2015-10-13_21-20-14](https://cloud.githubusercontent.com/assets/11447474/10472613/47d6ff8e-71f0-11e5-9fb0-da0ba4fd15b6.png)

Fresh site URL: https://sandboxclasses1.home.nyu.edu/portal/site/90345863-6b59-4598-83f9-0263595e8ee3
Existing site URL: https://sandboxclasses1.home.nyu.edu/portal/site/6d46de05-0ce1-4839-acad-16f0741ca87c

**Comment by steveswinsburg** [comment]
Ok this is because they still actually have grades, but it's blank - might be a comment there too.
The current fix checks if they have any grade records and under this particular condition, it will say they do. So rather than just checking if they have grades, we would need to inspect the contents of every grade they have to see if its blank, which is a further iteration - alternatively add a flag onto the wrapper for each of the students (GbStudentGradeInfo) which is updated when setting the grades - but that will need to be kept in sync when grades are later added - could get tricky.

We might be able to consolidate some of these iterations soon but I'm not going to fix this just yet, though the above is the likely solution.

**Comment by steveswinsburg** [comment]
This issue was moved to sakaiproject/sakai#1378
