### ISSUE TITLE
Add permission handling

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/gradebookNG#95]
The tool currently requires full/admin permissions. We need to introduce some permission checking.

**Comment by steveswinsburg** [comment]
Initial thoughts from the call this morning:
- When rendering the cells, check the permissions. If instructor, all good. If can edit, all good. If can view, just show score. If can't see anything, grey out the cell (or some other style), hide the comment bubble, hide the dropdown.
- Disable reordering/hiding for TA's. If you can view the category, show grade statistics
- If not allowed to view the category, don't show dropdown at all
- Check performance of this as a cell by cell check. If its bad we may need to fetch en masse then compare in memory.
- In the section info tool, if you assign a TA to a section, that TA should be able to grade that section.

**Comment by kyleblythe** [comment]
After our last call, I think that we arrived at the following permissions handling:
- If an instructor, all good.
- If a TA with the ability to grade a category, provide all grading abilities.
  - Remove ability to reorder item columns (both via drag 'n drop and the accessible options in items' drop-down menus).
- If a TA with the ability to view a given category, just show the scores.
  - Do not provide the ability to edit the score or add/edit comments.
  - Remove all options from GB item dropdown menu except for the ability to view grade statistics.

Additionally, if granular TA permissions have been granted, apply the following:
- If not given view/edit access to a specific category, do not show scores within the category's items. Grey out (or otherwise style) affected cells to denote that the user does not have view access to the scores. Remove all drop-downs at both the cell- and item-level. Remove comment bubbles (if applicable). Continue to show the items themselves, as well as their total points/due dates.
- If only given grade/view access to ONE section/group within the site, remove default "All Sections/Groups" filter on Grades screen, and instead default to the available section/group.
- If given grade/view access to TWO OR MORE sections/groups (but not all available sections/groups in the site), dynamically edit the "All Sections/Groups" filter title to instead reflect the sections/groups for which they have access (e.g. "Section 001, Section 004"). Hide all students for which the TA does not have grade/view access.

**Comment by steveswinsburg** [comment]
Closing this as the permission handling is being addressed in other tickets.
